name: push_app
description: PushApps app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  go_router: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/

  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: ru_RU
